apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-practice
  annotations:
    github.com/project-slug: Zaperex/react-practice
spec:
  type: other
  lifecycle: unknown
  owner: janus-authors
